name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
env:
  PYTHON_VERSION: "3.12"
  COMPOSE_FILE: docker-compose.yml

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: docker/setup-buildx-action@v1
        with:
          python-version: "3.12"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip install ruff
      - run: ruff check . --output-format=github

      - run: |
          echo "POSTGRES_USER=$(head /dev/urandom | tr -dc A-Za-z | head -c 8)" > .env
          echo "POSTGRES_PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16)" >> .env
          echo "POSTGRES_DB_AUTH=auth" >> .env
          echo "POSTGRES_DB_UNIVERSITY=university" >> .env
          echo "AUTH_SERVICE_INTERNAL_URL=http://auth:8000" >> .env
          echo "AUTH_SERVICE_API_URL=http://127.0.0.1:8000" >> .env
          echo "UNIVERSITY_SERVICE_INTERNAL_URL=http://university:8000" >> .env
          echo "UNIVERSITY_SERVICE_API_URL=http://127.0.0.1:8001" >> .env

      - run: docker compose up -d

      - run: docker build -t test-image:latest .

      - name: Install Allure
        run: |
          wget -O /tmp/allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.zip
          unzip /tmp/allure.zip -d /opt/
          echo "/opt/allure-2.34.1/bin" >> $GITHUB_PATH

      - run: |
          docker run --rm \
            --network host \
            --env-file .env \
            -v $(pwd)/allure-results:/back_api/allure-results \
            test-image:latest || true
          
      - run: |
          allure generate allure-results -o allure-report --clean
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true